name: jimmyledoux
favicon: null
layout_spectrum: 0.9934766707010567
typography_spectrum: 0.25828
title: 'We help business!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8244642049539834
  lightness: 0.6636590254493058
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
