name: jimmyledoux
favicon: null
layout_spectrum: 0.9934766707010567
typography_spectrum: 0.25921
title: 'We help business!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2e2e'
    - '#c2b1a9'
    - '#6b4947'
    - '#f4f2ff'
    - '#967264'
  brandStrength: 0.875
  lightness: 0.6636590254493058
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
